(function(){function h(b,a){return function(){return b.apply(a,arguments)}}function n(b,a){function d(){this.constructor=b}for(var c in a)o.call(a,c)&&(b[c]=a[c]);d.prototype=a.prototype;b.prototype=new d;b.u=a.prototype}var j,k,l,m,o=Object.prototype.hasOwnProperty;k=function(){function b(a,d){this.x=a;this.y=d}b.prototype.m=function(){return new b(this.x,this.y)};return b}();j=function(){function b(a,d){this.start=a;this.stop=d}b.prototype.s=function(){this.h=this.g=!1;this.g=" kk";this.stop.y-
this.start.y===0?(this.g=!0,this.a=0,this.d=this.stop.y):this.stop.x-this.start.x===0?this.h=!0:(this.a=(this.stop.y-this.start.y)/(this.stop.x-this.start.x),this.d=this.start.y-this.a*this.start.x)};b.prototype.D=function(a){var d,c;this.s();a.s();if(this.h&&a.h)return!1;else if(this.h)d=this.start.x,c=d*a.a+a.d;else if(a.h)d=a.start.x,c=d*this.a+this.d;else if(this.g&&a.g)return!1;else this.g?(c=this.start.y,d=(c-a.d)/a.a):(d=(this.d-a.d)/(a.a-this.a),c=(this.a*a.d-a.a*this.d)/(this.a-a.a));return this.t(d,
c)&&a.t(d,c)?!0:!1};b.prototype.t=function(a,d){var c,b,e,g;e=!1;b=this.start.x;c=this.stop.x;b>c&&(g=b,b=c,c=g);a>b&&a<c&&(e=!0);b=this.start.y;c=this.stop.y;b>c&&(g=b,b=c,c=g);d>b&&d<c&&(e=e&&!0);return e};return b}();m=function(){function b(a,d,c){this.start=a;this.stop=d;this.c=c;b.u.constructor.call(this,this.start,this.stop)}n(b,j);return b}();l=function(){function b(a,b){this.position=a;this.direction=b;this.r=!0;this.k=0;this.q=1.0E-4;this.j=this.l=0;this.color="rgb(255,255,255)";this.o=0;
this.c=!1;this.C=0;this.B="rgb(50,50,50)";this.b=[]}b.prototype.move=function(a){var b,c,f,e;this.lastPosition=this.position.m();c=!0;for(b=e=f=0;c;){this.direction+=this.l*a;b=this.q*a;f=this.position.x+b*Math.cos(this.direction);e=this.position.y+b*Math.sin(this.direction);if(f<0||f>1){this.direction=Math.PI-this.direction;c=!0;break}if(e<0||e>1){this.direction=-this.direction;c=!0;break}c=!1}this.position.x=f;this.position.y=e;this.b.push(new m(this.lastPosition.m(),this.position.m(),this.H()));
this.j+=b;this.q+=2.0E-7;return c};b.prototype.n=function(a){var b,c;if(this.b.length<3)return 0;for(b=0;b<this.b.length-2;){c=this.b[b];if(a.D(c))return c.c?1:2;b++}return 0};b.prototype.H=function(){var a;a=0.3/(14*(1-(this.q-5.0E-5)*2500));if(this.j>this.o+0.3&&this.c===!1)this.c=!0,this.C++;if(this.j>this.o+0.3+a&&this.c===!0)this.c=!1,this.o=this.j;return this.c};b.prototype.z=function(a){var b,c,f;if(this.b.length!==0)f=a.canvas.width,b=a.canvas.height,a.save(),c=this.b[this.b.length-1],a.beginPath(),
a.moveTo(c.start.x*f,c.start.y*b),a.lineTo(c.stop.x*f,c.stop.y*b),a.lineWidth=2,a.strokeStyle=this.c?this.B:this.color,a.stroke(),a.restore()};return b}();new (function(){function b(){this.version="0.1";this.f=[];this.canvas=document.getElementById("canvas");this.i=this.canvas.getContext("2d");this.k=document.getElementById("score");this.canvas.width=500;this.canvas.height=500;this.i.fillStyle="rgb(0,0,0)";this.i.fillRect(0,0,this.canvas.width,this.canvas.height);this.i.fillStyle="rgb(255,0,0)";document.onkeydown=
h(function(a){return this.F(a)},this);document.onkeyup=h(function(a){return this.G(a)},this);this.e={background:new Audio("background.ogg"),v:new Audio("bounce.ogg"),w:[new Audio("doh1.ogg"),new Audio("doh2.ogg"),new Audio("doh3.ogg"),new Audio("doh4.ogg"),new Audio("doh5.ogg"),new Audio("doh6.ogg")],A:new Audio("gameover.ogg"),L:new Audio("laugh.ogg"),load:new Audio("load.ogg"),start:new Audio("start.ogg"),I:new Audio("thread.ogg"),K:new Audio("wohoo.ogg")};this.e.K.play();setTimeout(h(function(){return this.start()},
this),500)}b.prototype.start=function(){this.e.start.play();this.f.push(new l(new k(0.2,0.2),0.4));this.p=(new Date).getTime()+100;return setInterval(h(function(){return this.J()},this),50)};b.prototype.J=function(){var a,b,c,f,e,g,i;c=(new Date).getTime();if(this.p>c)return!1;b=c-this.p;a=h(function(a){var c;if(a.r)return(c=a.move(b))&&this.e.v.play(),a.z(this.i),this.n(a)},this);i=this.f;e=0;for(g=i.length;e<g;e++)f=i[e],a(f);this.k.innerHTML="Score: "+f.k;this.p=c;return!0};b.prototype.n=function(a){var b,
c,f,e,g;b=h(function(b){b=b.n(a.b[a.b.length-1]);if(b===2)return a.r=!1,this.e.w[Math.floor(Math.random()*7)].play(),this.e.A.play();else if(b===1)return a.k+=1,this.e.I.play()},this);e=this.f;g=[];c=0;for(f=e.length;c<f;c++)a=e[c],g.push(b(a));return g};b.prototype.F=function(a){if(a.keyCode===37)return this.f[0].l=-0.0020;else if(a.keyCode===39)return this.f[0].l=0.0020};b.prototype.G=function(a){if(a.keyCode===37||a.keyCode===39)return this.f[0].l=0};return b}())}).call(this);
